spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/tinyDoctors
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect